### ISSUE TITLE
vue-cli-service: not found

### ISSUE THREAD

**Issue by vbhagat2net** [smartbugs/smartbugs-dashboard#32]
<pre><font color="#3465A4"><b>smartbugs-dashboard</b></font>$ npm run smartbugs

&gt; smartbugs-dashboard@1.0.0 smartbugs
&gt; npm run build &amp;&amp; node server.js

&gt; smartbugs-dashboard@1.0.0 build
&gt; vue-cli-service build

sh: 1: vue-cli-service: not found
</pre>

**Comment by talk2kabir** [comment]
> smartbugs-dashboard$ npm run smartbugs
> 
> > smartbugs-dashboard@1.0.0 smartbugs
> > npm run build && node server.js
> 
> 
> > smartbugs-dashboard@1.0.0 build
> > vue-cli-service build
> 
> sh: 1: vue-cli-service: not found

**Comment by Kalman-ui** [comment]
Was this fixed? Launching the dashboard has been a pain.

**Comment by jff** [comment]
Sorry, but this project is no longer maintained. Please consider using [Smartbugs](https://github.com/smartbugs/smartbugs)
