### ISSUE TITLE
POST http://localhost:5000/input-file-analysis net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by Kalman-ui** [smartbugs/smartbugs-dashboard#45]
When importing file for analysis, error in input-file-analysis (failed) net::ERR_CONNECTION_REFUSED

**Comment by Kalman-ui** [comment]
UPDATE: I fixed these Issues using the following before installing requirements.txt
`pip install antlr4-python3-runtime==4.8`

The issue now is that it returns empty results.

**Comment by jff** [comment]
Sorry, but this project is no longer maintained.
